package GUI;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author raffy
 */
public class addItem extends javax.swing.JFrame {

    /**
     * Creates new form addItem
     */
    public addItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        brandField = new javax.swing.JTextField();
        itemField = new javax.swing.JTextField();
        priceField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        form = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(469, 607));
        setMinimumSize(new java.awt.Dimension(469, 607));
        setPreferredSize(new java.awt.Dimension(469, 607));
        getContentPane().setLayout(null);

        brandField.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        brandField.setToolTipText("");
        getContentPane().add(brandField);
        brandField.setBounds(130, 150, 220, 20);

        itemField.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        getContentPane().add(itemField);
        itemField.setBounds(130, 270, 220, 20);

        priceField.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        getContentPane().add(priceField);
        priceField.setBounds(130, 380, 220, 20);

        submitButton.setOpaque(false);
        submitButton.setContentAreaFilled(false);
        submitButton.setBorderPainted(false);
        getContentPane().add(submitButton);
        submitButton.setBounds(80, 420, 320, 60);

        clearButton.setOpaque(false);
        clearButton.setContentAreaFilled(false);
        clearButton.setBorderPainted(false);
        getContentPane().add(clearButton);
        clearButton.setBounds(80, 480, 320, 60);

        form.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/forms/addItem Form.png"))); // NOI18N
        getContentPane().add(form);
        form.setBounds(80, 30, 320, 550);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/forms/iPhone.png"))); // NOI18N
        getContentPane().add(BG);
        BG.setBounds(0, -3, 480, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JTextField brandField;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel form;
    private javax.swing.JTextField itemField;
    private javax.swing.JTextField priceField;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
