package GUI;

import Logic.Bundle;
import Logic.BundleManager;
import Logic.Item;
import Logic.Office;
import Logic.OfficeManager;
import Logic.Supplier;
import Logic.SupplierManager;
import Logic.TransactionDB;
import Logic.WRInventory;
import java.awt.Cursor;
import java.util.Scanner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author raffy
 */
public class addOffice extends javax.swing.JFrame {

	private	Scanner inS;
	private	String sN;//supplier name
	private	String bN, N;//Items primary key
	private String u;// unit of bundle
	private String oN; // office name
	private String iV; // inVoice
	private Office tO;
        private Bundle c;
	private int m;// measurement of a bundle
	private Double pSP, sP;// sell price of a package, suppliers price for the item
	private	Double price;//price of Item
	private	WRInventory wR;//instance of inventory
	private	Item tempI;//temporary Item variable
	private	int bool;//to check if supplier exists in db
	private	SupplierManager sM;
	private OfficeManager oM = new OfficeManager();
	private TransactionDB sTM;
	private BundleManager bM;
        Pattern pattern = Pattern.compile("[!$&+,:;=?@#|]");
        Matcher matcher;
    public addOffice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerField = new javax.swing.JTextField();
        contactField1 = new javax.swing.JTextField();
        newCustomerButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        form = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(410, 630));
        setMinimumSize(new java.awt.Dimension(410, 630));
        setPreferredSize(new java.awt.Dimension(410, 630));
        getContentPane().setLayout(null);

        customerField.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        getContentPane().add(customerField);
        customerField.setBounds(90, 160, 220, 21);

        contactField1.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        getContentPane().add(contactField1);
        contactField1.setBounds(90, 270, 220, 21);

        newCustomerButton.setOpaque(false);
        newCustomerButton.setContentAreaFilled(false);
        newCustomerButton.setBorderPainted(false);
        newCustomerButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        newCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCustomerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(newCustomerButton);
        newCustomerButton.setBounds(50, 430, 315, 50);

        submitButton.setOpaque(false);
        submitButton.setContentAreaFilled(false);
        submitButton.setBorderPainted(false);
        submitButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton);
        submitButton.setBounds(50, 480, 315, 50);

        backButton.setOpaque(false);
        backButton.setContentAreaFilled(false);
        backButton.setBorderPainted(false);
        backButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(60, 40, 60, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/forms/button.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 430, 315, 50);

        form.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/forms/addOffice.png"))); // NOI18N
        getContentPane().add(form);
        form.setBounds(50, 10, 320, 580);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/forms/iPhone.png"))); // NOI18N
        getContentPane().add(BG);
        BG.setBounds(0, -3, 410, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        oN = customerField.getText().toUpperCase();
        boolean specialChar = pattern.matcher(oN).find();
        if(oM.getO(oN) != null || specialChar){
            promptErrorExistingOffice error = new promptErrorExistingOffice();
            error.setVisible(true);
            customerField.setText(null);
        }
        else if(oN.equals("") || contactField1.getText().equals("")){
            promptErrorExisting error1 = new promptErrorExisting();
            error1.setVisible(true);
        }
        else{
            tO = new Office(oN, contactField1.getText());
            oM.addO(tO);
            promptSuccess ok = new promptSuccess();
            ok.setVisible(true);
        }
        
        /*PROMPTS:
            CUSTOMER ALREADY EXISTS
            ADDED TO DB
        */
    }//GEN-LAST:event_submitButtonActionPerformed

    private void newCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCustomerButtonActionPerformed
        customerField.setText(null);
        contactField1.setText(null);
    }//GEN-LAST:event_newCustomerButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addOffice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField contactField1;
    private javax.swing.JTextField customerField;
    private javax.swing.JLabel form;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton newCustomerButton;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
