package GUI;


import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.awt.Cursor;
import java.awt.Graphics;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author raffy
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        buySupplyButton = new javax.swing.JButton();
        addSupplierButton = new javax.swing.JButton();
        addItemButton = new javax.swing.JButton();
        addOfficeButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        sellSupplyButton = new javax.swing.JButton();
        supplierTransactionsButton = new javax.swing.JButton();
        officeTransactionsButton = new javax.swing.JButton();
        viewPerSupplierButton = new javax.swing.JButton();
        viewPerOfficeButton = new javax.swing.JButton();
        viewAllIcon = new javax.swing.JLabel();
        viewNameIcon = new javax.swing.JLabel();
        viewTermsIcon = new javax.swing.JLabel();
        viewDateIcon = new javax.swing.JLabel();
        searchSupplierIcon = new javax.swing.JLabel();
        addItemIcon = new javax.swing.JLabel();
        addSupplierIcon = new javax.swing.JLabel();
        searchItemIcon = new javax.swing.JLabel();
        editItemIcon = new javax.swing.JLabel();
        settingsIcon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        addOfficeLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(819, 550));
        setResizable(false);
        getContentPane().setLayout(null);

        titleLabel.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(1, 1, 1));
        titleLabel.setText("SJT Trading");
        getContentPane().add(titleLabel);
        titleLabel.setBounds(20, 150, 170, 28);

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/FlipBoard74.png"))); // NOI18N
        getContentPane().add(logoLabel);
        logoLabel.setBounds(20, 60, 80, 80);

        buySupplyButton.setOpaque(false);
        buySupplyButton.setContentAreaFilled(false);
        buySupplyButton.setBorderPainted(false);
        buySupplyButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        buySupplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buySupplyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(buySupplyButton);
        buySupplyButton.setBounds(460, 330, 62, 62);

        addSupplierButton.setOpaque(false);
        addSupplierButton.setContentAreaFilled(false);
        addSupplierButton.setBorderPainted(false);
        addSupplierButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        addSupplierButton.setToolTipText("");
        addSupplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSupplierButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addSupplierButton);
        addSupplierButton.setBounds(460, 250, 62, 62);

        addItemButton.setOpaque(false);
        addItemButton.setContentAreaFilled(false);
        addItemButton.setBorderPainted(false);
        addItemButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        addItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addItemButton);
        addItemButton.setBounds(550, 250, 62, 62);

        addOfficeButton.setOpaque(false);
        addOfficeButton.setContentAreaFilled(false);
        addOfficeButton.setBorderPainted(false);
        addOfficeButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        addOfficeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOfficeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addOfficeButton);
        addOfficeButton.setBounds(370, 330, 62, 62);

        settingsButton.setOpaque(false);
        settingsButton.setContentAreaFilled(false);
        settingsButton.setBorderPainted(false);
        getContentPane().add(settingsButton);
        settingsButton.setBounds(750, 490, 50, 50);

        sellSupplyButton.setOpaque(false);
        sellSupplyButton.setContentAreaFilled(false);
        sellSupplyButton.setBorderPainted(false);
        sellSupplyButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        sellSupplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellSupplyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sellSupplyButton);
        sellSupplyButton.setBounds(550, 330, 62, 62);

        supplierTransactionsButton.setOpaque(false);
        supplierTransactionsButton.setContentAreaFilled(false);
        supplierTransactionsButton.setBorderPainted(false);
        supplierTransactionsButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        supplierTransactionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierTransactionsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(supplierTransactionsButton);
        supplierTransactionsButton.setBounds(370, 170, 62, 62);

        officeTransactionsButton.setOpaque(false);
        officeTransactionsButton.setContentAreaFilled(false);
        officeTransactionsButton.setBorderPainted(false);
        officeTransactionsButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        officeTransactionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                officeTransactionsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(officeTransactionsButton);
        officeTransactionsButton.setBounds(460, 170, 62, 62);

        viewPerSupplierButton.setOpaque(false);
        viewPerSupplierButton.setContentAreaFilled(false);
        viewPerSupplierButton.setBorderPainted(false);
        viewPerSupplierButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        viewPerSupplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPerSupplierButtonActionPerformed(evt);
            }
        });
        getContentPane().add(viewPerSupplierButton);
        viewPerSupplierButton.setBounds(550, 170, 62, 62);

        viewPerOfficeButton.setOpaque(false);
        viewPerOfficeButton.setContentAreaFilled(false);
        viewPerOfficeButton.setBorderPainted(false);
        viewPerOfficeButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        viewPerOfficeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPerOfficeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(viewPerOfficeButton);
        viewPerOfficeButton.setBounds(370, 250, 62, 62);

        viewAllIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/Books62.png"))); // NOI18N
        getContentPane().add(viewAllIcon);
        viewAllIcon.setBounds(370, 170, 62, 60);

        viewNameIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/Contacts62.png"))); // NOI18N
        getContentPane().add(viewNameIcon);
        viewNameIcon.setBounds(460, 170, 62, 62);

        viewTermsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/FoldersFlat62.png"))); // NOI18N
        getContentPane().add(viewTermsIcon);
        viewTermsIcon.setBounds(550, 170, 62, 60);

        viewDateIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/CalendarFlat62.png"))); // NOI18N
        getContentPane().add(viewDateIcon);
        viewDateIcon.setBounds(370, 250, 62, 60);

        searchSupplierIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/Drawer72.png"))); // NOI18N
        getContentPane().add(searchSupplierIcon);
        searchSupplierIcon.setBounds(460, 250, 62, 62);

        addItemIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/Ebay72.png"))); // NOI18N
        getContentPane().add(addItemIcon);
        addItemIcon.setBounds(550, 250, 62, 62);

        addSupplierIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/internet6.png"))); // NOI18N
        getContentPane().add(addSupplierIcon);
        addSupplierIcon.setBounds(370, 330, 62, 62);

        searchItemIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/files2.png"))); // NOI18N
        getContentPane().add(searchItemIcon);
        searchItemIcon.setBounds(460, 330, 62, 62);

        editItemIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/editor.png"))); // NOI18N
        getContentPane().add(editItemIcon);
        editItemIcon.setBounds(550, 330, 62, 62);

        settingsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/settings.png"))); // NOI18N
        settingsIcon.setToolTipText("");
        getContentPane().add(settingsIcon);
        settingsIcon.setBounds(750, 490, 48, 48);

        jLabel2.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("View Supplier Transactions ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(360, 230, 80, 17);

        jLabel3.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("View Office Transactions");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(450, 230, 80, 13);

        jLabel4.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("View a Supplier");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(550, 230, 77, 13);

        jLabel5.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("View an Office");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(360, 310, 71, 13);

        jLabel6.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Add Transaction");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(450, 310, 81, 13);

        jLabel7.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("Add Item");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(560, 310, 50, 13);

        addOfficeLabel.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        addOfficeLabel.setForeground(new java.awt.Color(254, 254, 254));
        addOfficeLabel.setText("Add Office");
        getContentPane().add(addOfficeLabel);
        addOfficeLabel.setBounds(370, 390, 60, 13);

        jLabel9.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(254, 254, 254));
        jLabel9.setText("Buying");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(470, 390, 50, 13);

        jLabel10.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(254, 254, 254));
        jLabel10.setText("Selling");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(560, 390, 35, 13);

        DateFormat timeFormat = new SimpleDateFormat("HH:mm");
        Date time = new Date();
        Time.setText(timeFormat.format(time));
        Time.setFont(new java.awt.Font("Brandon Grotesque Medium", 1, 56)); // NOI18N
        Time.setForeground(new java.awt.Color(224, 224, 224));
        getContentPane().add(Time);
        Time.setBounds(430, 20, 220, 60);

        DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
        Date date = new Date();
        Date.setText(dateFormat.format(date));
        Date.setFont(new java.awt.Font("Myriad Pro", 1, 15)); // NOI18N
        Date.setForeground(new java.awt.Color(224, 224, 224));
        getContentPane().add(Date);
        Date.setBounds(450, 80, 110, 30);

        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/noblur.jpeg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 220, 560);

        bgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bricks.jpg"))); // NOI18N
        getContentPane().add(bgImage);
        bgImage.setBounds(220, 0, 610, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addSupplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSupplierButtonActionPerformed
        addSupplier plusSupplier = new addSupplier();
        plusSupplier.setVisible(true);
    }//GEN-LAST:event_addSupplierButtonActionPerformed

    private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemButtonActionPerformed
        addItem plusItem = new addItem();
        plusItem.setVisible(true);
    }//GEN-LAST:event_addItemButtonActionPerformed

    private void addOfficeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOfficeButtonActionPerformed
        addOffice plusOffice = new addOffice();
        plusOffice.setVisible(true);
    }//GEN-LAST:event_addOfficeButtonActionPerformed

    private void buySupplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buySupplyButtonActionPerformed
        buySupply buy = new buySupply();
        buy.setVisible(true);
    }//GEN-LAST:event_buySupplyButtonActionPerformed

    private void sellSupplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellSupplyButtonActionPerformed
        sellSupply sell = new sellSupply();
        sell.setVisible(true);
    }//GEN-LAST:event_sellSupplyButtonActionPerformed

    private void supplierTransactionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierTransactionsButtonActionPerformed
        viewAllTransactionsSupplier viewsupp = new viewAllTransactionsSupplier();
        viewsupp.setVisible(true);
    }//GEN-LAST:event_supplierTransactionsButtonActionPerformed

    private void officeTransactionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_officeTransactionsButtonActionPerformed
        viewAllTransactionsOffice viewoffice = new viewAllTransactionsOffice();
        viewoffice.setVisible(true);
    }//GEN-LAST:event_officeTransactionsButtonActionPerformed

    private void viewPerSupplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPerSupplierButtonActionPerformed
        viewPerSupplier perSupplier = new viewPerSupplier();
        perSupplier.setVisible(true);
    }//GEN-LAST:event_viewPerSupplierButtonActionPerformed

    private void viewPerOfficeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPerOfficeButtonActionPerformed
        viewPerOffice perOffice = new viewPerOffice();
        perOffice.setVisible(true);
    }//GEN-LAST:event_viewPerOfficeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("empty-statement")
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date;
    private javax.swing.JLabel Time;
    private javax.swing.JButton addItemButton;
    private javax.swing.JLabel addItemIcon;
    private javax.swing.JButton addOfficeButton;
    private javax.swing.JLabel addOfficeLabel;
    private javax.swing.JButton addSupplierButton;
    private javax.swing.JLabel addSupplierIcon;
    private javax.swing.JLabel bgImage;
    private javax.swing.JButton buySupplyButton;
    private javax.swing.JLabel editItemIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton officeTransactionsButton;
    private javax.swing.JLabel searchItemIcon;
    private javax.swing.JLabel searchSupplierIcon;
    private javax.swing.JButton sellSupplyButton;
    private javax.swing.JButton settingsButton;
    private javax.swing.JLabel settingsIcon;
    private javax.swing.JButton supplierTransactionsButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel viewAllIcon;
    private javax.swing.JLabel viewDateIcon;
    private javax.swing.JLabel viewNameIcon;
    private javax.swing.JButton viewPerOfficeButton;
    private javax.swing.JButton viewPerSupplierButton;
    private javax.swing.JLabel viewTermsIcon;
    // End of variables declaration//GEN-END:variables

    private void dateAndTime(String format) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
