/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import Connection.DBconnection;
import Connection.DBconnectionImpl;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raffy
 */
public class viewPerSupplier extends javax.swing.JFrame {

    String search;
    DefaultTableModel tableQuery = new DefaultTableModel();
    //DefaultTableModel chartQuery = new DefaultTableModel();
    DefaultListModel officeListQuery = new DefaultListModel();
    DefaultTableModel itemListQuery = new DefaultTableModel();
    public viewPerSupplier() {
        initComponents();
        DBconnectionImpl dBConnection;
        Connection connection;
        
        //itemListQuery = (DefaultTableModel)itemTable.getModel();
        try {
                dBConnection = DBconnection.getInstance();
                connection = dBConnection.getConnection();
                String query = "select * from supplier";
                PreparedStatement preparedStatement = connection.prepareStatement(query);
                ResultSet rs = preparedStatement.executeQuery();
                while (rs.next()) {
                    officeListQuery.addElement(rs.getString("name"));
                }   
            } catch (SQLException ex) {
                Logger.getLogger(buySupply.class.getName()).log(Level.SEVERE, null, ex);
            }
        officeList.setModel(officeListQuery);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buyAndSellButton = new javax.swing.JButton();
        menuButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        officeList = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        viewAllOfficeButton = new javax.swing.JButton();
        viewPerOfficeButton = new javax.swing.JButton();
        viewAllSupplierButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewPerSupplier = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(915, 708));
        setMinimumSize(new java.awt.Dimension(915, 708));
        setPreferredSize(new java.awt.Dimension(915, 708));
        getContentPane().setLayout(null);

        buyAndSellButton.setOpaque(false);
        buyAndSellButton.setContentAreaFilled(false);
        buyAndSellButton.setBorderPainted(false);
        buyAndSellButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        buyAndSellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyAndSellButtonActionPerformed(evt);
            }
        });
        getContentPane().add(buyAndSellButton);
        buyAndSellButton.setBounds(10, 100, 50, 40);

        menuButton.setOpaque(false);
        menuButton.setContentAreaFilled(false);
        menuButton.setBorderPainted(false);
        menuButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(menuButton);
        menuButton.setBounds(10, 170, 50, 40);

        settingsButton.setOpaque(false);
        settingsButton.setContentAreaFilled(false);
        settingsButton.setBorderPainted(false);
        settingsButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(settingsButton);
        settingsButton.setBounds(10, 250, 50, 40);

        jScrollPane2.setViewportView(officeList);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(730, 150, 150, 350);

        jLabel3.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        jLabel3.setText("List of Suppliers: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(730, 120, 90, 13);

        searchButton.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchButton);
        searchButton.setBounds(770, 520, 90, 21);

        viewAllOfficeButton.setOpaque(false);
        viewAllOfficeButton.setContentAreaFilled(false);
        viewAllOfficeButton.setBorderPainted(false);
        viewAllOfficeButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        viewAllOfficeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllOfficeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(viewAllOfficeButton);
        viewAllOfficeButton.setBounds(250, 60, 180, 40);

        viewPerOfficeButton.setOpaque(false);
        viewPerOfficeButton.setContentAreaFilled(false);
        viewPerOfficeButton.setBorderPainted(false);
        viewPerOfficeButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        viewPerOfficeButton.setToolTipText("");
        viewPerOfficeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPerOfficeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(viewPerOfficeButton);
        viewPerOfficeButton.setBounds(610, 60, 180, 40);

        viewAllSupplierButton.setOpaque(false);
        viewAllSupplierButton.setContentAreaFilled(false);
        viewAllSupplierButton.setBorderPainted(false);
        viewAllSupplierButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        viewAllSupplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllSupplierButtonActionPerformed(evt);
            }
        });
        getContentPane().add(viewAllSupplierButton);
        viewAllSupplierButton.setBounds(80, 60, 160, 40);

        viewPerSupplier.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        viewPerSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice", "Name", "Date", "Terms", "Deadline", "Total"
            }
        ));
        jScrollPane1.setViewportView(viewPerSupplier);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 110, 630, 560);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Introse New Form Designs/View All Suppliers.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 683);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        search = officeList.getSelectedValue().toString().toUpperCase();
        DBconnectionImpl dBConnection;
        Connection connection;
        tableQuery = (DefaultTableModel)viewPerSupplier.getModel();
            try {
                dBConnection = DBconnection.getInstance();
                connection = dBConnection.getConnection();
                String query = "select * from sTransaction where name = '" + search + "'";
                PreparedStatement preparedStatement = connection.prepareStatement(query);
                ResultSet rs = preparedStatement.executeQuery();
                while (rs.next()) {
                    tableQuery.insertRow(tableQuery.getRowCount(), new Object[]{rs.getString("inVoice"), rs.getString("name"), rs.getString("date"),rs.getString("terms"), rs.getString("deadline"),rs.getString("total")});
                }   
            } catch (SQLException ex) {
                Logger.getLogger(buySupply.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void viewPerOfficeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPerOfficeButtonActionPerformed
        viewPerOffice perOffice  = new viewPerOffice();
        perOffice.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewPerOfficeButtonActionPerformed

    private void viewAllOfficeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllOfficeButtonActionPerformed
        viewAllTransactionsOffice allOffice = new viewAllTransactionsOffice();
        allOffice.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewAllOfficeButtonActionPerformed

    private void viewAllSupplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllSupplierButtonActionPerformed
        viewAllTransactionsSupplier allSupp = new viewAllTransactionsSupplier();
        allSupp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewAllSupplierButtonActionPerformed

    private void buyAndSellButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyAndSellButtonActionPerformed
        buySupply buy = new buySupply();
        buy.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buyAndSellButtonActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_menuButtonActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_settingsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewPerSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewPerSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewPerSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewPerSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewPerSupplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyAndSellButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton menuButton;
    private javax.swing.JList officeList;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton settingsButton;
    private javax.swing.JButton viewAllOfficeButton;
    private javax.swing.JButton viewAllSupplierButton;
    private javax.swing.JButton viewPerOfficeButton;
    private javax.swing.JTable viewPerSupplier;
    // End of variables declaration//GEN-END:variables
}
