/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import Connection.DBconnection;
import Implementation.BundleImpl;
import Implementation.SupplierImpl;
import Logic.Item;
import Logic.Manager;
import Logic.PriceBean;
import Logic.Supplier;
import java.awt.Color;
import java.math.BigInteger;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Raffy
 */
public class editP extends javax.swing.JFrame {

    /**
     * Creates new form editP
     */
    BigInteger bID, sID = null;
            String temp;
                String bN, n, u;
		Supplier s;
                PriceBean a;
                double p, p1;
                PriceBean tempI;
    DefaultTableModel tableQuery1 = new DefaultTableModel();
    DefaultTableModel tableQuery2 = new DefaultTableModel();
    private Connection connection;
    private DBconnection dBConnection;
    public editP() {
        initComponents();
        supp.setVisible(false);
        newsjt.setVisible(false);
        newsupp.setVisible(false);
        background2.setVisible(false);
        pane2.setVisible(false);
         try {
            dBConnection = DBconnection.getInstance();
            connection = dBConnection.getConnection();
            tableQuery1 = (DefaultTableModel)itemtable.getModel();
            String query = "select * from Item group by brandName,name;";
            PreparedStatement preparedStatement = connection.prepareStatement(query);
            ResultSet rs = preparedStatement.executeQuery();
            ArrayList<Item> bundle = new ArrayList();
            while (rs.next()) {
                tableQuery1.insertRow(tableQuery1.getRowCount(), new Object[]{
                    rs.getString("brandName"), rs.getString("name"), rs.getString("unit")
                });
            } 
        } catch (SQLException ex) {
            Logger.getLogger(BundleImpl.class.getName()).log(Level.SEVERE, null, ex);
        }
         

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        next1 = new javax.swing.JButton();
        pane1 = new javax.swing.JScrollPane();
        itemtable = new javax.swing.JTable();
        brand = new javax.swing.JTextField();
        item = new javax.swing.JTextField();
        unit = new javax.swing.JTextField();
        background1 = new javax.swing.JLabel();
        next2 = new javax.swing.JButton();
        pane2 = new javax.swing.JScrollPane();
        suppliertable = new javax.swing.JTable();
        supp = new javax.swing.JTextField();
        newsupp = new javax.swing.JTextField();
        newsjt = new javax.swing.JTextField();
        showprice = new javax.swing.JButton();
        prev = new javax.swing.JButton();
        confirm = new javax.swing.JButton();
        background2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 700));
        setMinimumSize(new java.awt.Dimension(700, 700));
        setPreferredSize(new java.awt.Dimension(700, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        next1.setOpaque(false);
        next1.setContentAreaFilled(false);
        next1.setBorderPainted(false);
        next1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next1ActionPerformed(evt);
            }
        });
        getContentPane().add(next1);
        next1.setBounds(460, 620, 80, 30);

        itemtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Brand", "Item", "Unit"
            }
        ));
        pane1.setViewportView(itemtable);

        getContentPane().add(pane1);
        pane1.setBounds(60, 60, 570, 310);

        brand.setOpaque(true);
        brand.setBorder(null);
        brand.setBackground(new Color(217, 219, 223));
        getContentPane().add(brand);
        brand.setBounds(320, 427, 140, 30);

        item.setOpaque(true);
        item.setBorder(null);
        item.setBackground(new Color(217, 219, 223));
        getContentPane().add(item);
        item.setBounds(320, 470, 140, 28);

        unit.setOpaque(true);
        unit.setBorder(null);
        unit.setBackground(new Color(217, 219, 223));
        getContentPane().add(unit);
        unit.setBounds(320, 518, 140, 30);

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-price-1.jpg"))); // NOI18N
        getContentPane().add(background1);
        background1.setBounds(0, 0, 700, 700);

        next2.setOpaque(false);
        next2.setContentAreaFilled(false);
        next2.setBorderPainted(false);
        getContentPane().add(next2);
        next2.setBounds(460, 620, 28, 12);

        suppliertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "SJT Price", "Supplier Price"
            }
        ));
        pane2.setViewportView(suppliertable);

        getContentPane().add(pane2);
        pane2.setBounds(60, 60, 570, 280);

        supp.setBorder(null);
        supp.setBackground(new Color(217, 219, 223));
        getContentPane().add(supp);
        supp.setBounds(300, 460, 130, 28);

        newsupp.setBorder(null);
        newsupp.setBackground(new Color(217, 219, 223));
        getContentPane().add(newsupp);
        newsupp.setBounds(300, 510, 130, 28);

        newsjt.setBorder(null);
        newsjt.setBackground(new Color(217, 219, 223));
        getContentPane().add(newsjt);
        newsjt.setBounds(300, 550, 130, 28);

        showprice.setOpaque(false);
        showprice.setContentAreaFilled(false);
        showprice.setBorderPainted(false);
        showprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpriceActionPerformed(evt);
            }
        });
        getContentPane().add(showprice);
        showprice.setBounds(460, 400, 90, 12);

        prev.setOpaque(false);
        prev.setContentAreaFilled(false);
        prev.setBorderPainted(false);
        getContentPane().add(prev);
        prev.setBounds(200, 620, 80, 12);

        confirm.setOpaque(false);
        confirm.setContentAreaFilled(false);
        confirm.setBorderPainted(false);
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        getContentPane().add(confirm);
        confirm.setBounds(310, 610, 120, 50);

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-price-2.jpg"))); // NOI18N
        background2.setText("jLabel1");
        getContentPane().add(background2);
        background2.setBounds(0, 0, 700, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void next1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next1ActionPerformed

		Manager mngr = new Manager();
		mngr.printNames();
                bN = brand.getText();
                n = item.getText();
                u = unit.getText();
                if(mngr.getB(bN, n, u) == null)
                 System.out.println("No such bundle exists");
		bID = mngr.getB(bN, n, u).getItemID();
                mngr.printPriceBeans(bID);
                background1.setVisible(false);
                next1.setVisible(false);
                next2.setVisible(true);
                background2.setVisible(true);
                brand.setVisible(false);
                item.setVisible(false);
                unit.setVisible(false);
                pane1.setVisible(false);
                pane2.setVisible(true);
                supp.setVisible(true);
                newsjt.setVisible(true);
                newsupp.setVisible(true);
                background2.setVisible(true);

                        try {
            dBConnection = DBconnection.getInstance();
            connection = dBConnection.getConnection();
            tableQuery2 = (DefaultTableModel)suppliertable.getModel();
            String query = "select s.name, p.userPrice, p.SupplierPrice from item as i "
                    + "inner join prices as p "
                    + "on i.itemId = p.itemId "
                    + "inner join supplier as s "
                    + "on s.supplierId = p.supplierId "
                    + "where i.itemId = " + bID;
            PreparedStatement preparedStatement = connection.prepareStatement(query);
            
            ResultSet rs = preparedStatement.executeQuery();
            ArrayList<Supplier> s = new ArrayList<Supplier>();
            while (rs.next()) {
                tableQuery2.insertRow(tableQuery2.getRowCount(), new Object[]{
                    rs.getString("s.name"), rs.getString("userPrice"), rs.getString("SupplierPrice"),
                });
            } 
        } catch (SQLException ex) {
            Logger.getLogger(SupplierImpl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_next1ActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        Manager mngr = new Manager();                
                    System.out.print("Enter Supplier:");
                    s = mngr.getS(supp.getText().toUpperCase());
                    if(s!=null){
                        sID = s.getID();
                        System.out.println(sID+" "+bID);
                        if(mngr.getP(bID, sID)!=null){
                            tempI = mngr.getP(bID, sID);
                            System.out.println("Supplier's pricing: "+tempI.getSupplierPrice());
                            System.out.println("SJT's pricing: "+tempI.getUserPrice());
                            System.out.print("Enter new Supplier's pricing: ");
                            p = Integer.parseInt(newsupp.getText());
                            System.out.print("Enter new SJT's pricing: ");
                            p1 = Integer.parseInt(newsjt.getText());
                            mngr.editP(new PriceBean(bID, sID, p, p1));
                            this.dispose();
                        }
                        else
                            System.out.println("Pricing does not exists");
                    }
                    else
                        System.out.print("Supplier does not exists");
                    
    }//GEN-LAST:event_confirmActionPerformed

    private void showpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpriceActionPerformed
        Manager mngr = new Manager();
        s = mngr.getS(supp.getText().toUpperCase());
        sID = s.getID();

    }//GEN-LAST:event_showpriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JTextField brand;
    private javax.swing.JButton confirm;
    private javax.swing.JTextField item;
    private javax.swing.JTable itemtable;
    private javax.swing.JTextField newsjt;
    private javax.swing.JTextField newsupp;
    private javax.swing.JButton next1;
    private javax.swing.JButton next2;
    private javax.swing.JScrollPane pane1;
    private javax.swing.JScrollPane pane2;
    private javax.swing.JButton prev;
    private javax.swing.JButton showprice;
    private javax.swing.JTextField supp;
    private javax.swing.JTable suppliertable;
    private javax.swing.JTextField unit;
    // End of variables declaration//GEN-END:variables
}
