/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import Connection.DBconnection;
import Implementation.BundleImpl;
import Implementation.ItemImpl;
import Logic.Item;
import Logic.Manager;
import java.awt.Color;
import java.math.BigInteger;
import java.util.Scanner;
import Logic.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Raffy
 */
public class InventoryGUI extends javax.swing.JFrame {

    /**
     * Creates new form Inventory
     */
    private Scanner inS;
    private Manager mngr = new Manager();
    DefaultTableModel supplyListQuery;
    DefaultTableModel tableQuery1 = new DefaultTableModel();
    DefaultTableModel tableQuery2 = new DefaultTableModel();
    DefaultTableModel tableQuery3 = new DefaultTableModel();
    DefaultTableModel tableQuery4 = new DefaultTableModel();
    private Connection connection;
    private DBconnection dBConnection;
    
    public InventoryGUI() {
        initComponents();
        try {
            tableQuery1 = (DefaultTableModel)inventoryTable.getModel();
            dBConnection = DBconnection.getInstance();
            connection = dBConnection.getConnection();
            String query = "select s.name, i.brandname, i.name, p.supplierPrice, i.stock from item as i "
                    + "inner join prices as p "
                    + "on i.itemId = p.itemId "
                    + "inner join supplier as s "
                    + "on p.supplierId = s.supplierId;";
            PreparedStatement preparedStatement = connection.prepareStatement(query);
            ArrayList<Item> items = new ArrayList<>();
            //preparedStatement.executeUpdate();
            ResultSet rs = preparedStatement.executeQuery();
            while (rs.next()) {
                tableQuery1.insertRow(tableQuery1.getRowCount(), new Object[]{
                    rs.getString("s.name"), rs.getString("brandName"), rs.getString("i.name"),
                    rs.getDouble("supplierPrice"), rs.getInt("stock")
            });
            }   
        } catch (SQLException ex) {
            Logger.getLogger(ItemImpl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        all = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        customer = new javax.swing.JButton();
        supplier = new javax.swing.JButton();
        customerT = new javax.swing.JButton();
        supplierT = new javax.swing.JButton();
        instructions = new javax.swing.JButton();
        jpane = new javax.swing.JScrollPane();
        inventoryTable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchTable = new javax.swing.JTable();
        background1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 672));
        setMinimumSize(new java.awt.Dimension(1200, 672));
        setPreferredSize(new java.awt.Dimension(1200, 672));
        getContentPane().setLayout(null);

        all.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        all.setOpaque(false);
        all.setContentAreaFilled(false);
        all.setBorderPainted(false);
        getContentPane().add(all);
        all.setBounds(280, 110, 50, 50);

        edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit.setOpaque(false);
        edit.setContentAreaFilled(false);
        edit.setBorderPainted(false);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit);
        edit.setBounds(850, 120, 80, 30);

        searchField.setBorder(null);
        searchField.setBackground(new Color(180, 69, 67));
        getContentPane().add(searchField);
        searchField.setBounds(60, 120, 170, 30);

        customer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        customer.setOpaque(false);
        customer.setContentAreaFilled(false);
        customer.setBorderPainted(false);
        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });
        getContentPane().add(customer);
        customer.setBounds(80, 170, 170, 70);

        supplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        supplier.setOpaque(false);
        supplier.setContentAreaFilled(false);
        supplier.setBorderPainted(false);
        supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierActionPerformed(evt);
            }
        });
        getContentPane().add(supplier);
        supplier.setBounds(80, 240, 170, 70);

        customerT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        customerT.setOpaque(false);
        customerT.setContentAreaFilled(false);
        customerT.setBorderPainted(false);
        getContentPane().add(customerT);
        customerT.setBounds(80, 457, 170, 70);

        supplierT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        supplierT.setOpaque(false);
        supplierT.setContentAreaFilled(false);
        supplierT.setBorderPainted(false);
        getContentPane().add(supplierT);
        supplierT.setBounds(80, 385, 170, 70);

        instructions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        instructions.setOpaque(false);
        instructions.setContentAreaFilled(false);
        instructions.setBorderPainted(false);
        getContentPane().add(instructions);
        instructions.setBounds(80, 530, 170, 70);

        inventoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier Name", "Brand Name", "Item Name", "Supplier Price", "Stock"
            }
        ));
        jpane.setViewportView(inventoryTable);

        getContentPane().add(jpane);
        jpane.setBounds(290, 200, 620, 460);

        searchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(searchTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(290, 200, 620, 460);

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inventory-final.jpg"))); // NOI18N
        background1.setText("jLabel1");
        getContentPane().add(background1);
        background1.setBounds(0, 0, 1200, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
        CustomerGUI custom = new CustomerGUI();
        custom.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_customerActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        editP edit = new editP();
        edit.setVisible(true);
    }//GEN-LAST:event_editActionPerformed

    private void supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierActionPerformed
        SupplierGUI supplier = new SupplierGUI();
        supplier.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_supplierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton all;
    private javax.swing.JLabel background1;
    private javax.swing.JButton customer;
    private javax.swing.JButton customerT;
    private javax.swing.JButton edit;
    private javax.swing.JButton instructions;
    private javax.swing.JTable inventoryTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jpane;
    private javax.swing.JTextField searchField;
    private javax.swing.JTable searchTable;
    private javax.swing.JButton supplier;
    private javax.swing.JButton supplierT;
    // End of variables declaration//GEN-END:variables
}
