/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import Logic.Item;
import Logic.Manager;
import java.awt.Color;
import java.util.Scanner;

/**
 *
 * @author Raffy
 */
public class newB extends javax.swing.JFrame {

    /**
     * Creates new form newBundle
     */
    private Scanner inS;
    private Manager mngr = new Manager();
    
    public newB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idealstock = new javax.swing.JTextField();
        unitprice = new javax.swing.JTextField();
        storelocation = new javax.swing.JTextField();
        selllocation = new javax.swing.JTextField();
        itemperunit = new javax.swing.JTextField();
        unit = new javax.swing.JTextField();
        item = new javax.swing.JTextField();
        brand = new javax.swing.JTextField();
        confirm = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(560, 400));
        setMinimumSize(new java.awt.Dimension(560, 400));
        setPreferredSize(new java.awt.Dimension(560, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        idealstock.setBorder(null);
        idealstock.setBackground(new Color(217, 219, 223));
        getContentPane().add(idealstock);
        idealstock.setBounds(360, 76, 140, 30);

        unitprice.setBorder(null);
        unitprice.setBackground(new Color(217, 219, 223));
        getContentPane().add(unitprice);
        unitprice.setBounds(360, 139, 140, 20);

        storelocation.setBorder(null);
        storelocation.setBackground(new Color(217, 219, 223));
        getContentPane().add(storelocation);
        storelocation.setBounds(360, 200, 140, 30);

        selllocation.setBorder(null);
        selllocation.setBackground(new Color(217, 219, 223));
        getContentPane().add(selllocation);
        selllocation.setBounds(360, 265, 140, 30);

        itemperunit.setBorder(null);
        itemperunit.setBackground(new Color(217, 219, 223));
        getContentPane().add(itemperunit);
        itemperunit.setBounds(100, 265, 140, 30);

        unit.setBorder(null);
        unit.setBackground(new Color(217, 219, 223));
        getContentPane().add(unit);
        unit.setBounds(100, 200, 140, 30);

        item.setBorder(null);
        item.setBackground(new Color(217, 219, 223));
        getContentPane().add(item);
        item.setBounds(100, 139, 140, 20);

        brand.setBorder(null);
        brand.setBackground(new Color(217, 219, 223));
        getContentPane().add(brand);
        brand.setBounds(100, 77, 140, 30);

        confirm.setToolTipText("");
        confirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirm.setOpaque(false);
        confirm.setContentAreaFilled(false);
        confirm.setBorderPainted(false);
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        getContentPane().add(confirm);
        confirm.setBounds(220, 320, 120, 50);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/supplier-bundle.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 560, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        Manager manage = new Manager();
        String bN, n, u, l;
        int inID, norm, m;
        double uP;
	bN = brand.getText().toUpperCase();
        n = item.getText().toUpperCase();
        u = unit.getText().toUpperCase();
        if(manage.getB(bN, n, u)!=null){
            System.out.println("Error, bundle already exists");
            System.out.println("Enter Again");
        }
        else{
            m = Integer.parseInt(itemperunit.getText().toUpperCase());
            norm = Integer.parseInt(idealstock.getText().toUpperCase());
            uP = Double.parseDouble(unitprice.getText().toUpperCase());
            l = storelocation.getText().toUpperCase();
	    manage.addB(new Item(bN, n, u, norm, l, m));
            if(manage.getI(n, bN)==null){
                System.out.print("Enter where item is to be sold for walkin transactions: ");
                //l = inS.next().toUpperCase();
                l = "BOOKSTORE1";
                manage.addItem(new Item(bN, n, u, norm, l, m, uP));
            }
        }
    }//GEN-LAST:event_confirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextField brand;
    private javax.swing.JButton confirm;
    private javax.swing.JTextField idealstock;
    private javax.swing.JTextField item;
    private javax.swing.JTextField itemperunit;
    private javax.swing.JTextField selllocation;
    private javax.swing.JTextField storelocation;
    private javax.swing.JTextField unit;
    private javax.swing.JTextField unitprice;
    // End of variables declaration//GEN-END:variables
}
