/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import Logic.Account;
import Logic.Manager;
import java.awt.Color;
import java.util.Date;
import java.util.Scanner;

/**
 *
 * @author Raffy
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    private Scanner inS;
    private Manager mngr = new Manager();
    
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        first = new javax.swing.JTextField();
        last = new javax.swing.JTextField();
        position = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        month = new javax.swing.JTextField();
        day = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        confirm = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(550, 405));
        setMinimumSize(new java.awt.Dimension(550, 405));
        setPreferredSize(new java.awt.Dimension(550, 405));
        getContentPane().setLayout(null);

        first.setBorder(null);
        first.setBackground(new Color(217, 219, 223));
        getContentPane().add(first);
        first.setBounds(100, 77, 140, 30);

        last.setBorder(null);
        last.setBackground(new Color(217, 219, 223));
        getContentPane().add(last);
        last.setBounds(100, 139, 140, 20);

        position.setBorder(null);
        position.setBackground(new Color(217, 219, 223));
        getContentPane().add(position);
        position.setBounds(100, 200, 140, 30);

        year.setBorder(null);
        year.setBackground(new Color(217, 219, 223));
        getContentPane().add(year);
        year.setBounds(360, 76, 140, 30);

        month.setBorder(null);
        month.setBackground(new Color(217, 219, 223));
        getContentPane().add(month);
        month.setBounds(360, 139, 140, 20);

        day.setBorder(null);
        day.setBackground(new Color(217, 219, 223));
        getContentPane().add(day);
        day.setBounds(360, 200, 140, 30);

        first.setBorder(null);
        first.setBackground(new Color(217, 219, 223));
        getContentPane().add(password);
        password.setBounds(360, 275, 140, 30);

        first.setBorder(null);
        first.setBackground(new Color(217, 219, 223));
        getContentPane().add(username);
        username.setBounds(100, 275, 140, 30);

        confirm.setToolTipText("");
        confirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirm.setOpaque(false);
        confirm.setContentAreaFilled(false);
        confirm.setBorderPainted(false);
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        getContentPane().add(confirm);
        confirm.setBounds(220, 320, 120, 50);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signup.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, -2, 550, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
                String temp;
		Account a = new Account();
		int yearBirth, monthBirth, dayBirth;
		Date d;
                a.setFirstName(first.getText().toUpperCase());
		a.setLastName(last.getText().toUpperCase());
		a.setPosition(position.getText().toUpperCase());
		yearBirth = (Integer.parseInt(year.getText()))-1900;
		monthBirth = monthToInt(month.getText());
		dayBirth = Integer.parseInt(day.getText());
		d = new Date(yearBirth, monthBirth, dayBirth);
		a.setBirthDay(d);
                temp = username.getText();
                if(mngr.checkAccount(temp)){
                    //username exists error
                    username.setText(null);
                } else{
                    a.setUserName(temp);
                    a.setPassWord(password.getText());
                    mngr.addAccount(a);
                    //success
                }
                login log = new login();
                log.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_confirmActionPerformed

    	public int monthToInt(String month){
		if(month.equals("JANUARY"))
			return 0;
		else if(month.equals("FEBRUARY"))
			return 1;
		else if(month.equals("MARCH"))
			return 2;
		else if(month.equals("APRIL"))
			return 3;
		else if(month.equals("MAY"))
			return 4;
		else if(month.equals("JUNE"))
			return 5;
		else if(month.equals("JULY"))
			return 6;
		else if(month.equals("AUGUST"))
			return 7;
		else if(month.equals("SEPTEMBER"))
			return 8;
		else if(month.equals("OCTOBER"))
			return 9;
		else if(month.equals("NOVEMBER"))
			return 10;
		else if(month.equals("DECEMBER"))
			return 11;
        return -1;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton confirm;
    private javax.swing.JTextField day;
    private javax.swing.JTextField first;
    private javax.swing.JTextField last;
    private javax.swing.JTextField month;
    private javax.swing.JTextField password;
    private javax.swing.JTextField position;
    private javax.swing.JTextField username;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
